### ISSUE TITLE
idid tried multiplayer 2d but failed

### ISSUE THREAD

**Issue by stickylab** [Alteruna/Multiplayer-FPS-Template#1]
![image](https://github.com/Alteruna/Multiplayer-FPS-Template/assets/87752832/aad1d7ed-73c4-4bed-98e4-883c66eeb6b8)

**Comment by SimonAlteruna** [comment]
Your issue is about the 2D platformer, This is the FPS template.

The issue is already pending for the asset store and a solution is on Discord [here](https://discord.com/channels/730034774575677452/897764325631086632/1126949398534963302).

**Comment by stickylab** [comment]
Checkout your asset store project.....

Pada tanggal Min, 16 Jul 2023 18.41, SimonAlteruna ***@***.***>
menulis:
