### ISSUE TITLE
Can I use this in commercial game projects

### ISSUE THREAD

**Issue by DSOE1024** [Alteruna/Multiplayer-FPS-Template#2]
I'm making multiplayer FPS games, Can I use this in commercial game projects ?

**Comment by SimonAlteruna** [comment]
Yes, commercial use is allowed. See [/README.md](https://github.com/Alteruna/Multiplayer-FPS-Template/blob/main/README.md) and [/Assets/AlterunaFPS/README.md](https://github.com/Alteruna/Multiplayer-FPS-Template/blob/main/Assets/AlterunaFPS/README.md) for more details.
