### ISSUE TITLE
i can't run the game

### ISSUE THREAD

**Issue by BOTGrzes** [Alteruna/Multiplayer-FPS-Template#3]
i installed the template and i get these errors:
`Assets\AlterunaFPS\Scripts\CinemachineVirtualCameraInstance.cs(12,10): error CS0246: The type or namespace name 
'CinemachineVirtualCamera' could not be found (are you missing a using directive or an assembly reference?)`
`Assets\AlterunaFPS\Scripts\CinemachineVirtualCameraInstance.cs(11,10): error CS0246: The type or namespace name 'CinemachineVirtualCamera' could not be found (are you missing a using directive or an assembly reference?)`
`Assets\AlterunaFPS\Scripts\CinemachineVirtualCameraInstance.cs(12,10): error CS0246: The type or namespace name 'CinemachineVirtualCamera' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by SimonAlteruna** [comment]
I'm sorry for not getting back to you sooner, it looks like you do not have the Cinemachine package installed. Please install it from the package manager.
